sudo: required
services:
  - docker

before_install:
  - docker build -t y0j/react-tests -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true y0j/react-tests npm run test

after_success:
  - docker build -t y0j/multi-client ./client
  - docker build -t y0j/multi-nginx ./nginx
  - docker build -t y0j/multi-server ./server
  - docker build -t y0j/multi-worker ./worker

# Login to docker CLI
- echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin

# Take images and push them to the docker hub
- docker push y0j/multi-client
- docker push y0j/multi-nginx
- docker push y0j/multi-server
- docker push y0j/multi-worker