---
sudo: required
services:
  - docker

before_install:
  - docker build -t sktymnxr6ifoux/react-tests -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true sktymnxr6ifoux/react-tests npm run test

after_success:
  - docker build -t sktymnxr6ifoux/multi-client ./client
  - docker build -t sktymnxr6ifoux/multi-nginx ./nginx
  - docker build -t sktymnxr6ifoux/multi-server ./server
  - docker build -t sktymnxr6ifoux/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to the docker hub
  - docker push sktymnxr6ifoux/multi-client
  - docker push sktymnxr6ifoux/multi-nginx
  - docker push sktymnxr6ifoux/multi-server
  - docker push sktymnxr6ifoux/multi-worker
